modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="vore_mod"
version="2.0.0"
displayName="Vore Mod"
displayURL="https://jasontheleech.itch.io/minecraft-vore-mod"
credits="Created with MCreator - https://mcreator.net/about \ntest"
authors="Jason"
description="Eat and be eatd."

[[dependencies.vore_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




